(lang dune 3.20)

(name aoc)

(generate_opam_files true)

(source
 (github ratakor/aoc))

(authors "Ratakor <ratakor@disroot.org>")

(license ISC)

(package
 (name aoc)
 (synopsis "Advent of Code 2025")
 (depends ocaml containers ppx_expect))
